//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urlaubsantrag.AssistenzService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AssistenzService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AntragEmpfangen", ReplyAction="http://tempuri.org/IService/AntragEmpfangenResponse")]
        Urlaubsantrag.AssistenzService.AntragEmpfangenResponse AntragEmpfangen(Urlaubsantrag.AssistenzService.AntragEmpfangenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AntragEmpfangen", ReplyAction="http://tempuri.org/IService/AntragEmpfangenResponse")]
        System.Threading.Tasks.Task<Urlaubsantrag.AssistenzService.AntragEmpfangenResponse> AntragEmpfangenAsync(Urlaubsantrag.AssistenzService.AntragEmpfangenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AntragEmpfangen", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AntragEmpfangenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UrlaubsantragService.Contract.Urlaubsantrag antrag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string correlationId;
        
        public AntragEmpfangenRequest() {
        }
        
        public AntragEmpfangenRequest(UrlaubsantragService.Contract.Urlaubsantrag antrag, string correlationId) {
            this.antrag = antrag;
            this.correlationId = correlationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AntragEmpfangenResponse {
        
        public AntragEmpfangenResponse() {
        }
    }
}
